### ISSUE TITLE
TODO Feature : add mongo database connection with mongoose 

### ISSUE THREAD

**Issue by c4nzin** [canmertinyo/nest-pad#2]
## Feature : 
 Need to add mongo db connection with mongoose 

## Docs : 
[Nestjs mongodb](https://docs.nestjs.com/techniques/mongodb)
[Mongoose](https://mongoosejs.com/)

## Breakdown : 
- [x] Implement database config service
- [x] Implement database module
- [x] Completion of the task

**Comment by c4nzin** [comment]
Done ✔
