### ISSUE TITLE
TODO Feature: get specific notepad with by id route

### ISSUE THREAD

**Issue by c4nzin** [canmertinyo/nest-pad#31]
## Feature 
This feature needs to be added to the project.

## Need to be completed
- [x] Implementing the Controller
- [x] Implementing the Service
- [x] Completion of the task

**Comment by c4nzin** [comment]
Current task

**Comment by c4nzin** [comment]
Done.
commit : https://github.com/canmertinyo/memo-pal/commit/7d9d775fde0b292962c1459e9669c3b18c504d91
