### ISSUE TITLE
TODO Feature: add note boilerplate

### ISSUE THREAD

**Issue by c4nzin** [canmertinyo/nest-pad#36]
## Feature : 
add note boilerplate

## Need to be completed
- [x] Implementing the Controller
- [x] Implementing the Service
- [x] Implementing the Module
- [x] Completion of the task

**Comment by c4nzin** [comment]
Done

**Comment by c4nzin** [comment]
Commit : https://github.com/canmertinyo/memo-pal/commit/bfb538a9535df8c72bf8f2db6ce25bf70ce3a122
